### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by keshav1228** [BadWolf22/QuizizzHelper#5]
its not working anymore for me, pls help!

**Comment by BadWolf22** [comment]
It appears as if bookmarkify.it is not functioning right now. Nothing I can do about that atm. I will switch to using GitHub as a host when I get the chance, but there are many issues that I am running into and there is a lot of code refactoring to do.

**Comment by BadWolf22** [comment]
Just as an update, it looks like it is working again.
